apiVersion: apps.example.com/v1
kind: MyApp
metadata:
  labels:
    app.kubernetes.io/name: myapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: myapp-sample
spec:
  # TODO(user): Add fields here
